messenger4j:
  appSecret: fe2fd14eca55327f0810e1ef2366ad48
  verifyToken: test_token
  pageAccessToken: EAATmxQx1md4BAPpjcpXelp9K05GoH6PITbXTZApuUJtePaPZASRMJfypAHjqA5ob1CneUfH3k7pLnZBjTk3pbJR1iPexASh3FZAKybZBDayvKQeSmXUuJiT2gjN9QnWFZAWA6tf0LZB3sH2JMGWgUuFPfxKD8ZAKEVZCIm9V0wLRZCWAZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO