messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAJbzHPZAIn0FSuswzb2T0kCwHuOgMEBmlq6eGOlBfzxthPxVT9qpwazUsNxpUujI91AU8ZChSHCCrZCv73Pqn6SFo8AZBd7yZCOflZAu8VzVPpS82zQrjZArPw0Q2oPReg2l63dRnZC7SbclA00arvv2Lw4quh6TvgZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO