messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAH0duQ6wVSdnyZBvkSkBNoM4ghTVTn5N88FFXfmVWCnAu7zcur4ajl5B8CoKvr9MgAhCIoZC1oudLneghMaASXFmvIeU6E0IQZBqhtxckeTcSbebTa9AtqV3Y8xZBa7UgCgHN5ny8AtHlJgLd7f44I0M2jQ18wZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO