messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAMUdHmjr024OW590UwdFk0HcHniMW4Yavy2EuhhBcUUi7Eu90BV2ZBH8Bg6WM1wP2FiZA9nYP7kLWZBojtfnX5aiA27CtzjpzYRjNCC2923vZB9MY6o5HC2eyKfb0jutr9N7BHW8u17o9yAfWTSZAaVUY9osqwgZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO