messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAFKZBurzJvD7tQUZCzubxNNPbQgEmDLLtHTZBKGeT22v61wIXeIUT8iBMsY5ZCGXGkjZA8F4ZCSMEzGp7eLBdDYblDuPRhHTB5hnkIQjAIXvgL8IdxK0R3ZAPgkzikJ4Cl23QdYNxfilKnVfmuFCPXOsKB3S8UYhwZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO