messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAPjEE3G8nGXHwV0ZBrkjqnoymkC0VUE8CDL0vMx2dWhsG7YFMfZAyaKtXkpAwTkuRroPZANP96rcrDvjrLR9Qy4hb5aRk9kOQtBzJQ9KOjS74kRRF41X9sIoPeiXKgK05LO63uyJv1xxWOQwZBGdhULFN8shdQZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO