messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAFVpsZBhwGdMAhKghSI7sf9V00YcyDHRXwkEBJsTqETTHyIZCleBhZANcjynZAl5nD671ixtRNm3FeAhgMpaRQQhBEpNZC5ZBZAYWTy9svQ3h7juWGkxm44Aimt9k3ReH24MGXMbg0C9ZBwgahleU4zc1e1iyXq0ugZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO