messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAK3fDm7ZAhIOgzoY1AzQT2fmi3q7947s9AmJpZAMjdPggetsbP3XQgaxYgfPoxVuN2XZCuw137BaaHilfFv9hJhtGPXShUjgWfwOxEL1OF8xXkA1dWB8CgrZB3ggASXcDp3Ax85ZBwg9sTqsDC0GUO3va9hdJaQZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO