messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAHDN3SNA3sHA7bPejvyar8ujkDRNTpKNbp6jwZABGhNuSe64ypZAb3nMQYTVTLtyM4EZCq9x2hhTZBb7ZBpo2oIFcyi3KpFXNr7BpeXKYZBZBM4iwisE3t1hZBOSxB8Lb6J5nhjn4TCV8SXwytLiRXrhNZBQhHo2FbQZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO