messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAGjGVJKm7cdtrb0ynzZAuSXTw3JFTLcALWM7bEFsiXo0sIShfjRNxgyOTx0TBScyHb6dZB7ZAK5gvNos0ZAt94PwXQCxhK1lNwVKEWpEMT43JaoiZB2yIKobPE7PnL4k2MLDZCcY78RL7CJZBLkZB23sxTJo6RORvAZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO