messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBABqLRxz3Dx61Uq4iAn3cZC98aXw27p5iRFyCZCGbLnDIMZBS4pQAOTG65EVHlyi2lgUDZB2M7ZC9ni6sXaZCZAp5UIFWM44RZCv9Rn1n5erjKhIbo3k0QbHC3fG1mdKDaMjnqVP9WFu7Hb1iZB0krrLzbZCH2Htae8iwZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO