messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAGOhd4ExZC1qrDkv9WqoiFwtt3Vgf6vTpAZCS05C5zWMtToKnXz3II0LCzlZBuGipYYSDOYDORgZAQsWwJG0Wef7f1DAcFZBoC6qwpoFcn3Bv9ey0zwyyfnUTzAb7qiZB9ZAzOlKxXtARrUZAT7jDPh6fpFqMY8eHQZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO