messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBABcMMHrTh63erwYLyZBDkytO7knwjxeKIK8s1U3C8z7f83zHoTwCGohRYBm9wxZApAh0lrtXKEPIeLoTG2pA68DKnLHqdvAfwCySNyAEP3ynwDU5EdTfaSZCPsAEOQvdMtwjyZBJEUR2EZCQWqtcjqNvMzsZBszwZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO