messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAFJ3l4GOZBZBncFOOrD4NMEhT4sYRDLNPDmExZC6FZCfZBdHSsxGe7qGxE9ipPcZBTCJrVcwyZAPFB1ZBlbpb9WYOrNaP3DWKDQCDnOymxtt9stYoZAh60ymbgT5Eb7XIOhLknyiZC0TGbBAHdZBKVT47Ag2wZAZBE42AnwZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO