messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAAxM91xZCuffkqeD9HwqPrkx8BM0t5VcVL3NMUa3TDwiaL1bfM7Jd4CSLhcIcKCazeHoWXIRh0hSr0sKfXxKT5lFO8UpsJsiLwUohGiZB728b46UL1O4GhNM5loAUmERGkKkKKjvdE88MPg3pZB3I8yRrd67wZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO