messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBANMkPTOg0vIVomR14maDDjVbME2g46nPVIutXmDn4FqIXEmSGQRo9fmNUhGPlhSfByoZALZATWfgiHDDZAcrd5nwLY1o7y4vXUaTjYQ33gdCiqG1c7irfiZBGUHFc3fVE7CGWnBGQqgx80kuzK5Ih6fgJjAIvAZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO