messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAJYJwdLBkZAX8WB2lr4XZBU02lsegcZBYXHLZBHDE2DKBnv3KJzzHwZBC8pZBMsbz0QJBZAnmydYZA2oetQUJKRKrW97c4UeApzCAGBMGjmC1Dr8XVZCKK6BBlFJ34f4qdIdXHMluGo3ZAKVXVUe7CjvZBJVW6ma2Bl4gZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO