messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAL8q8QjjQlCgE162krnq7ve3rB7JWPn9UJ204Wyaz144hf4qrxETKZB7TA8YBI1naZBW5EpI6W5Kc1FFWCAtrPlBaKGw3GmKDVqSlqVbcu18odHwe4k0Avri4EcvaIj4lZBZCHNrVUrxFjtX8oQupvECVEIYZAgZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO