messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBADIYkjdZCo8YMtkvsWFsyGzpy8yYWA5pBPobBbYDP6fQ2HOuFt97ZAgliQFSHMBa6zYGc1Il1ng3ddrJ0uOrm9TvfLEbF8g49qWTATkVzuPCbLAENpJbZAvHSsmad4THwYuGx5O2pGCY7n46wTEwmUMDgu2kAZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO