messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAM37cimz7cVZB0828kX3aMAnsXbNutiY6bGVcI0pucavcuhLo3stRdseMO1mluOfqPSSC2L2SgIiifxBagobTVj84LO25ZCQCB9eZBZB9fZCGAiFHGi5GTe3dmSDs79bSPXIteAIZCktqvFv3CshuZAYZAaD1h5A6gZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO