messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBABjZCMUWG5Qg0WoTJHmGFgGa411rhxNiHyUCDbW1OcZCbepOFDXFgXJpZBEeIBOmnf3ZBgk2401P22fZAA2EseiY8HLpCMYy7AdCKu2bd7jZAaHomTtRXn68Ap7mVszZCZBotBc1WHXghHbdqZBN8ncNRbDIMj3XZBgwZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO