messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAGFrzvH320LicZBsrLSroZCGrVu1GkKf3fjaNyApNqrEiBQvjxZC1CnZB56wjWfNi0soCL9rIyVKOmAIaupPs3a9VSmrvetw2yNwOYKiVWYexon21xNgcyh6Cc6oWO2ZAxNGAlVtsnN6ovzRLI7jYXHByJZCs7KAZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO