messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAEJLecLXC76dw1I3kwYuUHPhIZAKL6aPk7LTZAqU8ENvjJpYKDw9dA6vi48OI0e1NaxZCPFdDf6Br6r6EZCMJOyy0vtx5avMdOXPXePlqGbZAMJkL9b4EJGDbEkfPcknKpFJpQoNnuJRh6qlnjUfwla1S9tTPMQZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO