messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAN6h0gDBaPMX6b4XCOsiNFZCSDHKzITy9S00SHvGjZBXl9P3eZCWVMnflE5poM2B5AjCoZCasevcFgj5aiNA3I7iXgFp2AwNKrenSGOD7lQZCnKICWWOvT36UiBR5r7vXVM25sjLbGo6bJYFreqHzAAX2oK8cyQZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO