messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAPJYqxSfgOfnRssj4NVmGTxbFRWctv4gzgKvw27ozZAmvXkxJlpZB9zKUlZBAkW6d5bcJkgzGnCcy8cFbnW2alWp665Dss26qvAue7wULbkN8wJxFaZBqZArOg2enfQA9ejuZBKLiqu6PD1IG8sGIgRmUBcapcpQZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO