messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAOBHSkZCzi5g1mQ0ODRHZAPcsT6VFb7Dvbt1kaTdOMj3e0Ym3VtAlZCEBIltBjqbFedzsPAyzIwCCWw5tkFZASnp2HoakW97NKKrphWvD6AxRLTkEDxkZCrhA1MY8bTwsCYU5NLgFkTobT1cR1g9tdTTPUXhvigZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO