messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBACB3HCFsPq4ZBjwkYfBx5Lup6w62hEZCFWxTZBqB5LHcOIf7VlZCNlowuZAKFN3OKIUjRynJfsv4GY54vUPGD9S0DsZB2gseHQTQ4p18V1giGbfwbgC9s3YtPDuta6jcmz6zWiHEdV59BoXUyKGC0PZAweVS9qc8gZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO