messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAPITvoJrwYtxR6ZB48Uq4Ga3wbdu2uJ98RFbEp8ZCxkwzt2ZCUK9mhXneZCjS33qAqIZABe6eRhZBTHVVUMJrg2ofoeqHQd9oLRbCHl1NTMad0vTIk0OWvHwEdZCIVTALtO9ZBJC71ESNjVVQAqwMJOKUZBzes8ZCRDQZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO